<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eCoreTest" nsURI="http://www.example.org/eCoreTest" nsPrefix="eCoreTest">
  <eClassifiers xsi:type="ecore:EClass" name="Tasks"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataCollectionTask" eSuperTypes="#//Tasks">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//FormatType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//CollectionSchema"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataIntegrationTask" eSuperTypes="#//Tasks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Source" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataCleaningTask" eSuperTypes="#//Tasks"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAnalysis" eSuperTypes="#//Tasks"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline" upperBound="-1"
        eType="#//Pipeline" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FormatType">
    <eLiterals name="JSON"/>
    <eLiterals name="JSV" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Tasks" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//DataCollectionTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="RestService" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="USER" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PWD" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PORT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="USER" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PWD" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeSchema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSchema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SchemaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaType">
    <eLiterals name="string"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="date" value="2"/>
  </eClassifiers>
</ecore:EPackage>
